project:
  type: website
  output-dir: ../_site/faq

filters:
  - fontawesome

website:
  title: "FAQ"
  navbar:
    background: primary
    logo: "https://world.openfoodfacts.org/images/logos/off-logo-horizontal-light.svg"
    left:
      - text: '<span id="language-selector-trigger">üåê Language ‚ñº</span>'
        href: "#"
    right:
      - icon: github
        href: https://github.com/openfoodfacts
  repo-url: https://github.com/openfoodfacts/cms-test
  repo-subdir: faq
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    toc-depth: 2
    from: markdown+autolink_bare_uris
    include-after-body: language-selector.html

